sudo: required

language: php

php:
  - 7.1

services:
  - docker

git:
  depth: false

addons:
  hosts:
    - hmctskm.docker

before_install:
  - composer install
  - cd web/app/themes/hmcts-km
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - rm -Rf node_modules bower_components
  - cd ../../../..

install:
  - docker-compose -f docker-compose-travis.yml up -d
  - gem install dory
  - dory up
  - dory status
  - docker-compose -f docker-compose-travis.yml exec wordpress features/seed-database.sh -d

script:
  - vendor/bin/behat

notifications:
  email: false
